before_script:
- 'echo TRAVIS_BRANCH: $TRAVIS_BRANCH'
- 'echo TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST'
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- pip3 install -r requirements.txt
- python3 ./generate-matrix.py >/dev/null && git diff --exit-code
env:
  matrix:
  - TOMCAT_VERSION=8.0 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE_IMAGE= LUCEE_VERSION=5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=
  - TOMCAT_VERSION=8.0 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE_IMAGE=-alpine LUCEE_VERSION=5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=
language: python
python: 3.6
script:
- python3 -u build-images.py
services:
- docker
sudo: required
